import usefull packages

In [1]:
import pandas as pd
import numpy as np

In [2]:
def generate_data_col(i: int):
    mean, width = i*1.5+1, i*0.5+0.5
    print("mean: %.1f, standard deviation: %.1f" % (mean, width))
    return np.random.normal(mean, width, 300)

In [3]:
n_sample = 300
data = []

for i in range(6):
    data.append(generate_data_col(i))

mean: 1.0, standard deviation: 0.5
mean: 2.5, standard deviation: 1.0
mean: 4.0, standard deviation: 1.5
mean: 5.5, standard deviation: 2.0
mean: 7.0, standard deviation: 2.5
mean: 8.5, standard deviation: 3.0


In [4]:
data = np.array(data).T

print(data)

[[ 1.23100053  2.34953852  1.86232493  6.86326491  7.51755328  7.86179528]
 [ 1.68127582  2.08628907  1.37712046  5.83361112  6.75199398  8.99117062]
 [ 1.73013939  0.50145603  4.39218787  5.78921744  7.57711779 11.02813687]
 ...
 [ 0.68069556  1.45178005  3.36142576  2.6469357   6.86938018 10.21835666]
 [ 1.2387378   2.97321506  3.82154182  7.38298617  6.72829153  6.76048074]
 [ 1.05780239  3.07946423  6.22409168  7.50891255  7.87297871  4.33068711]]


In [5]:
columns = ["c"+str(i+1) for i in range(6)]
print(columns)
df = pd.DataFrame(data, columns=columns)
print(df)

['c1', 'c2', 'c3', 'c4', 'c5', 'c6']
           c1        c2        c3        c4         c5         c6
0    1.231001  2.349539  1.862325  6.863265   7.517553   7.861795
1    1.681276  2.086289  1.377120  5.833611   6.751994   8.991171
2    1.730139  0.501456  4.392188  5.789217   7.577118  11.028137
3    1.212081  2.778229  6.483949  6.593586   2.955380  11.682219
4    1.370364  3.824751  4.311832  7.559515   7.930648   9.647643
..        ...       ...       ...       ...        ...        ...
295  0.565253  0.078708  3.959810  3.366636   8.210645  12.809488
296  1.158481  3.248337  6.771628  2.801578  13.499591   4.687396
297  0.680696  1.451780  3.361426  2.646936   6.869380  10.218357
298  1.238738  2.973215  3.821542  7.382986   6.728292   6.760481
299  1.057802  3.079464  6.224092  7.508913   7.872979   4.330687

[300 rows x 6 columns]


In [6]:
df["c6"] = df["c6"].apply(np.round).astype(int)
print(df["c6"])

0       8
1       9
2      11
3      12
4      10
       ..
295    13
296     5
297    10
298     7
299     4
Name: c6, Length: 300, dtype: int64


In [7]:
df["c3"] = -1 * df["c3"]
df["c4"] = -1 * df["c4"]
print(df["c3"], df["c4"])

0     -1.862325
1     -1.377120
2     -4.392188
3     -6.483949
4     -4.311832
         ...   
295   -3.959810
296   -6.771628
297   -3.361426
298   -3.821542
299   -6.224092
Name: c3, Length: 300, dtype: float64 0     -6.863265
1     -5.833611
2     -5.789217
3     -6.593586
4     -7.559515
         ...   
295   -3.366636
296   -2.801578
297   -2.646936
298   -7.382986
299   -7.508913
Name: c4, Length: 300, dtype: float64


In [8]:
df.to_csv("artificial_dataset.csv", index=False)